[package]
name = "speed-of-music"
version = "0.1.0"
authors = ["Filip Paul≈Ø <ing.fenix@seznam.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minimp3 = "0.5.0"