[package]
name = "speed-of-music"
version = "0.1.0"
authors = ["Filip Paul≈Ø <ing.fenix@seznam.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
minimp3 = "0.5.0"
pbr = "1.0.3"
rayon = "1.4.0"
# num_cpus = "1.13.0"
# rustfft = "3.0.1"
# basic_dsp_vector = "0.8.2"
